version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
  # admin_queue:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   command: 'php artisan queue:work'
  #   depends_on:
  #     - admin_db

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: Events_Management
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: rootroot
    volumes:
      - ./../dbdata:/var/lib/mysql
    ports:
      - 33066:3306
  
  phpmyadmin:
    restart: always
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
  
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: always
    volumes:
      - ./../data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1